# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/playground-logging/
    overwrite: yes
file_exists_behavior : OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: script/run_new_was.sh
      timeout: 180
      runas: ubuntu
    - location: script/health_check.sh
      timeout: 180
      runas: ubuntu
    - location: script/switch.sh
      timeout: 180
      runas: ubuntu
