spring:
  servlet:
    multipart:
      max-file-size: 20MB # 파일 하나당 크기
      max-request-size: 20MB # 전송하려는 총 파일 크기

cloud:
  aws:
    credentials:
      accessKey: AKIAQFBK5SIWUKJ3SMC6
      secretKey: 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
    s3:
      bucket: igobucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


