### https://kauth.kakao.com/oauth/authorize?client_id=fdb42734830cbb186c8221bf3acdd6c6&redirect_uri=http://localhost:8080/kakao/callback&response_type=code

### GetToken
POST http://localhost:8080/api/post
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNDQxMDg3OTI1IiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjY0Nzg3NzUwfQ.ixFeYdcJgcbnVdnsz9aI02mmHtG85KW94rL3EYCvSWc
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjUzOTA3NTB9.jGSTKkcr8WGbunQnYCtVYrUmBdb-rAKCwpgPbwbRoDc
Content-Type: application/json

{ "title":"dd", "content":"<p><img src=\"https://nondis3.s3-ap-northeast-2.amazonaws.com/imgSatOct012022190538GMT0900KoreanStandardTime.jpeg\" alt=\"image\" contenteditable=\"false\"> 이히하</p><img src=\"https://nondis3.s3-ap-northeast-2.amazonaws.com/imgSatOct012022194635GMT0900한국표준시.jpeg\" alt=\"image\" contenteditable=\"false\">", "amount":123, "tags":["interest","money","region"], "mapData":"mapData" }

### Heart
POST http://localhost:8080/api/heart/1
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNDQxMDg3OTI1IiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjY0Nzg3NzUwfQ.ixFeYdcJgcbnVdnsz9aI02mmHtG85KW94rL3EYCvSWc
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjUzOTA3NTB9.jGSTKkcr8WGbunQnYCtVYrUmBdb-rAKCwpgPbwbRoDc
Content-Type: application/json


### Report
POST http://localhost:8080/api/report/1
Authorization: BEARER eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIyNDQxMDg3OTI1IiwiYXV0aCI6IlJPTEVfTUVNQkVSIiwiZXhwIjoxNjY0Nzg3NzUwfQ.ixFeYdcJgcbnVdnsz9aI02mmHtG85KW94rL3EYCvSWc
RefreshToken: eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2NjUzOTA3NTB9.jGSTKkcr8WGbunQnYCtVYrUmBdb-rAKCwpgPbwbRoDc
Content-Type: application/json

